---
- hosts: default
  become: yes
  vars:

    nodejs_version: "6.x"

  tasks:
    - shell: ansible-galaxy install {{item}}
      with_items:
        - geerlingguy.nodejs
        - geerlingguy.elasticsearch
        - geerlingguy.redis
        